module.exports = {
  PUPPETEER_ARGS: [
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-dev-shm-usage",
    "--disable-accelerated-2d-canvas",
    "--no-first-run",
    "--no-zygote",
    "--single-process",
    "--disable-gpu",
    "--disable-web-security",
    "--disable-features=VizDisplayCompositor",
    "--disable-extensions",
    "--disable-default-apps",
    "--disable-sync",
    "--disable-background-networking",
    "--disable-background-timer-throttling",
    "--disable-backgrounding-occluded-windows",
    "--disable-breakpad",
    "--disable-client-side-phishing-detection",
    "--disable-component-update",
    "--disable-domain-reliability",
    "--disable-features=AudioServiceOutOfProcess",
    "--disable-ipc-flooding-protection",
    "--disable-notifications",
    "--disable-permissions-api",
    "--disable-site-isolation-trials",
    "--disable-software-rasterizer",
    "--disable-speech-api",
    "--disable-webgl",
    "--enable-features=NetworkService,NetworkServiceInProcess",
    "--metrics-recording-only",
    "--mute-audio",
    "--no-default-browser-check",
    "--no-pings",
    "--password-store=basic",
    "--use-gl=swiftshader",
    "--use-fake-ui-for-media-stream",
    "--disable-blink-features=AutomationControlled",
  ],

  MIME_TYPE_MAP: {
    'application/pdf': 'pdf',
    'application/msword': 'doc',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
    'application/vnd.ms-excel': 'xls',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'xlsx',
    'application/vnd.ms-powerpoint': 'ppt',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'pptx',
    'application/zip': 'zip',
    'application/x-rar-compressed': 'rar',
    'text/plain': 'txt',
    'text/csv': 'csv',
    'application/json': 'json',
    'application/xml': 'xml',
  },

  BOT_COMMANDS: {
    INFO: '!info',
    TEST: '!test',
    PING: '!ping',
  },

  MESSAGE_DELAY: 500,
  RECONNECT_DELAY: 5000,
  REINIT_DELAY: 1000,
};